services:
  traefik:
    image: traefik:3.4
    command:
      "--configFile=/etc/traefik/traefik.yml"
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik-access.log:/var/log/traefik-access.log"

  private-communicating-service:
    container_name: private-communicating-service
    entrypoint: ["uvicorn", "--host", "0.0.0.0", "--reload", "public.index:app"]
    environment:
      PRIVATE_SERVICE_URL: "https://www.google.com"
    image: communicating-service:latest
    ports:
      - "80:8000"
    volumes:
      - ./services/communicating-service:/app

  private-non-communicating-service:
    container_name: private-non-communicating-service
    entrypoint: ["uvicorn", "--host", "0.0.0.0", "--reload", "public.index:app"]
    image: non-communicating-service:latest
    ports:
      - "81:8000"
    volumes:
      - ./services/non-communicating-service:/app

  public-communicating-service:
    container_name: public-communicating-service
    entrypoint: ["uvicorn", "--host", "0.0.0.0", "--reload", "public.index:app"]
    environment:
      PRIVATE_SERVICE_URL: "https://www.google.com"
    image: communicating-service:latest
    ports:
      - "80:8000"
    volumes:
      - ./services/communicating-service:/app
